version: "3.9"

name: ebridge-oracle
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  ebridge-oracle-entityhandler:
    build:
      dockerfile: ../Dockerfile
      args: &default-args
        branch: "${BRANCH}"
        repo: "${REPO}"
        servicename: AElf.EventHandler
    restart: on-failure:5
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./entityhandler.json:/App/appsettings.json:rw
    network_mode: service:redis
  ebridge-oracle-priceworker:
    build:
      dockerfile: ../Dockerfile
      args:
        <<: *default-args
        servicename: AElf.PriceWorker
    restart: on-failure:5
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./priceworker.json:/App/appsettings.json:rw
    network_mode: service:redis